#!/bin/bash

# Colors
RED="\e[31m"
GREEN="\e[32m"
BLUE="\e[34m"
YELLOW="\e[33m"
PURPLE="\e[35m"
CYAN="\e[36"
RESET="\e[0m"

# Variables
version="RSVCE"
verse_range=$(printf "%s" "$3" | grep -oE "[0-9]+-[0-9]+")
verse_result=
# Use as version if version argument exist
if [ $# -eq 4 ]; then
  version=$4
fi

# Functions
printVerses()
{
	echo
}

getVerseAmount()
{
	echo
}

center()
{
	local raw
	local columns
	local text

	raw="$*"
	columns=$(tput cols)
	text=$(printf "%s" "$raw" | sed -E "s/\\\e[[0-9;]*[m]//g" | fold -s)

	printf "%*b\n" $(((${#text} + columns) / 2)) "$raw"
}


# Help menu
usage()
{
	echo "Usage: ./bible_verse book_name chapter verse [version]"
	echo -e "Example:
		${GREEN}bible_verse${RESET} John 3 16 KJV (ESV by default)
		${GREEN}bible_verse${RESET} John 3 16-21 KJV"
	echo -e "For books with numbers infront of them, ex: 1 Peter
		${GREEN}bible_verse${RESET} 1Peter 1 1-2 SBLGNT"
	echo -e "For output to image
		${GREEN}bible_verse${RESET} John 3 16 KJV | python3 verseonimage.py
		${GREEN}bible_verse${RESET} John 3 16-21 KJV | python3 verseonimage.py
		${GREEN}bible_verse${RESET} John 3 16-21 NKJV | python3 versetoimage.py <your image.png>"
	exit
}

# Request to biblegateway and parse response
request_and_parse(){
	bible=$(curl -s "https://www.biblegateway.com/passage/?search=$1+$2:$3&version=$4")
	verse_text=$(printf "%s" "$bible" | sed -n 's/.*<meta property="og:description" content="\(.*\)".*/\1/p')
	verse_result="${verse_result} ${verse_text}"
}

# Checks and adjustments for a certain scraping block
if [ -n "$verse_range" ]; then
	number1=$(printf "%s" "$verse_range" | cut -d'-' -f1)
	number2=$(printf "%s" "$verse_range" | cut -d'-' -f2)
	range_count=$((number2 - number1))
	if [ $range_count -ge 5 ]; then 
		request_and_parse "$1" "$2" "$number1-$((number1+4))" "$version"
		while [ $((number1+5)) -le "$number2" ]; do
			number1=$((number1+5))
			request_and_parse "$1" "$2" "$number1-$number2" "$version"
		done
		printf "%s\n" "$verse_result"
		exit 0 
	fi
fi

main()
{
	# Process arguments

	# Check for help
	if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
		usage
	fi

	# Ensure the correct number of arguments have been submitted.
	if [ $# -lt 3 ]; then
	  printf "%b\n" "${RED}Error: Incorrect number of arguments.${RESET}"
	  exit 1
	fi


	center "${YELLOW}Hello, there! This is a really long text.${RESET}"
	request_and_parse "$1" "$2" "$3" "$version"
	# Prints book name,chapter,verse,and version
	# printf "%s\n" "$1 $2 $3 $version"

	printf "%s\n" "=========="
	center "${BLUE}$verse_result${RESET}"
	printf "%s\n" "=========="
	request_and_parse "$1" "$2" "$3" "$version"
	printf "%s\n" "$verse_result"

}

main "$@"
